//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulBilgiİslem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenci()
        {
            this.Odev = new HashSet<Odev>();
        }
    
        public int OgrenciNo { get; set; }
        public string OgrenciAdiSoyadi { get; set; }
        public string Sinifi { get; set; }
        public string Bolumu { get; set; }
        public string Adresi { get; set; }
        public string Telefon { get; set; }
        public string OkulNo { get; set; }
        public int VeliNo { get; set; }
    
        public virtual Veli Veli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odev> Odev { get; set; }
    }
}
