//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulBilgiİslem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Veli()
        {
            this.Ogrenci = new HashSet<Ogrenci>();
        }
    
        public int VeliNo { get; set; }
        public string VeliAdiSoyadi { get; set; }
        public string Yakinlik { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string EgitimDurumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ogrenci> Ogrenci { get; set; }
    }
}
